services:
  master:
    build:
      context: .
      dockerfile: master/Dockerfile
    container_name: master
    ports:
      - "5000:5000"

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    depends_on:
      - master
    deploy:
      replicas: 3
    ports:
      - "0:6000"

